### PR TITLE
Add Laravel 6.* compatibility and hours diff

### PR DESCRIPTION
**Pull request by dniccum**
* Updates the Carbon version requirement to compatible with Laravel 5.7 applications
* Adds new method to get date diff in hours

### CODE REVIEW

**Comment by dvlpp** [comment]
Mmm, I don't understand: Laravel 5.7 requires `^1.26.3` version of Carbon, so this should be ok as it is, no? (https://github.com/laravel/framework/blob/5.7/composer.json)

**Comment by dniccum** [comment]
Adds support for Carbon 2.0 and adds new method to get hours between.

**Comment by dvlpp** [comment]
Cool, thanks! May I ask you to add tests for your new method? (see https://github.com/code16/carbon-business-days/blob/master/tests/CarbonBusinessDaysBetweenTest.php for instance)

**Comment by dniccum** [comment]
@dvlpp Please review.

**Comment by dvlpp** [comment]
Thanks

**Pull request merged**
